% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Oct-2016 09:29:24
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
                                                         

CommonModelConfiguration = Simulink.ConfigSet;
CommonModelConfiguration.set_param('SystemTargetFile', 'grt.tlc');
CommonModelConfiguration.set_param('GenerateComments', 'on');
CommonModelConfiguration.set_param('SimulinkBlockComments', 'on');
CommonModelConfiguration.set_param('ShowEliminatedStatement', 'off');
CommonModelConfiguration.set_param('ForceParamTrailComments', 'off');
CommonModelConfiguration.set_param('GenerateReport', 'off');
CommonModelConfiguration.set_param('LaunchReport', 'off');
CommonModelConfiguration.set_param('OptimizeBlockIOStorage', 'on');
CommonModelConfiguration.set_param('ExpressionFolding', 'on');
CommonModelConfiguration.set_param('UpdateModelReferenceTargets', ['IfO' ...
                                    'utOfDateOrStructuralChange']);
CommonModelConfiguration.set_param('ProdHWDeviceType', '32-bit Generic');
CommonModelConfiguration.set_param('DefaultParameterBehavior', ['Inline' ...
                                    'd']);
CommonModelConfiguration.set_param('EnableMemcpy', 'on');
CommonModelConfiguration.set_param('SaveFinalState', 'off');
CommonModelConfiguration.set_param('SignalLogging', 'on');
CommonModelConfiguration.set_param('TargetUnknown', 'off');
CommonModelConfiguration.set_param('EnableConcurrentExecution', 'off');
CommonModelConfiguration.set_param('LoadExternalInput', 'off');
CommonModelConfiguration.set_param('LoadInitialState', 'off');
CommonModelConfiguration.set_param('SaveTime', 'on');
CommonModelConfiguration.set_param('SaveState', 'off');
CommonModelConfiguration.set_param('SaveOutput', 'on');
CommonModelConfiguration.set_param('LimitDataPoints', 'on');
CommonModelConfiguration.set_param('DSMLogging', 'on');
CommonModelConfiguration.set_param('ReturnWorkspaceOutputs', 'off');
CommonModelConfiguration.set_param('SupportNonFinite', 'on');
CommonModelConfiguration.set_param('MatFileLogging', 'on');
CommonModelConfiguration.set_param('GRTInterface', 'off');
CommonModelConfiguration.set_param('CombineOutputUpdateFcns', 'on');
CommonModelConfiguration.set_param(['ModelReferenceMinAlgLoopOccurrence' ...
                                    's'], 'off');
CommonModelConfiguration.set_param('SolverType', 'Variable-step');
CommonModelConfiguration.set_param('AutoInsertRateTranBlk', 'off');
CommonModelConfiguration.set_param('ExtMode', 'off');
CommonModelConfiguration.set_param('ArtificialAlgebraicLoopMsg', ['warn' ...
                                    'ing']);
CommonModelConfiguration.set_param('BlockReduction', 'on');
CommonModelConfiguration.set_param('BooleanDataType', 'on');
CommonModelConfiguration.set_param('BufferReuse', 'on');
CommonModelConfiguration.set_param('BusObjectLabelMismatch', 'warning');
CommonModelConfiguration.set_param(['CheckExecutionContextPreStartOutpu' ...
                                    'tMsg'], 'off');
CommonModelConfiguration.set_param(['CheckExecutionContextRuntimeOutput' ...
                                    'Msg'], 'off');
CommonModelConfiguration.set_param('CheckMatrixSingularityMsg', 'none');
CommonModelConfiguration.set_param('CheckSSInitialOutputMsg', 'on');
CommonModelConfiguration.set_param('ConditionallyExecuteInputs', 'on');
CommonModelConfiguration.set_param('ConsistencyChecking', 'none');
CommonModelConfiguration.set_param('DataBitsets', 'off');
CommonModelConfiguration.set_param('EfficientFloat2IntCast', 'off');
CommonModelConfiguration.set_param('FcnCallInpInsideContextMsg', ['Enab' ...
                                    'leAllAsError']);
CommonModelConfiguration.set_param('GenCodeOnly', 'off');
CommonModelConfiguration.set_param('TargetLangStandard', ['C89/C90 (ANS' ...
                                    'I)']);
CommonModelConfiguration.set_param('CodeReplacementLibrary', 'None');
CommonModelConfiguration.set_param('InheritedTsInSrcMsg', 'warning');
CommonModelConfiguration.set_param('InlineInvariantSignals', 'on');
CommonModelConfiguration.set_param('Int32ToFloatConvMsg', 'warning');
CommonModelConfiguration.set_param('IntegerOverflowMsg', 'warning');
CommonModelConfiguration.set_param('IntegerSaturationMsg', 'warning');
CommonModelConfiguration.set_param('InvalidFcnCallConnMsg', 'error');
CommonModelConfiguration.set_param('LifeSpan', 'inf');
CommonModelConfiguration.set_param('LocalBlockOutputs', 'on');
CommonModelConfiguration.set_param('MaxConsecutiveZCsMsg', 'error');
CommonModelConfiguration.set_param('MaxIdLength', 31);
CommonModelConfiguration.set_param('ModelReferenceDataLoggingMessage', ...
                                    'warning');
CommonModelConfiguration.set_param('ModelReferenceIOMismatchMessage', ['n' ...
                                    'one']);
CommonModelConfiguration.set_param('ModelReferenceIOMsg', 'none');
CommonModelConfiguration.set_param(['ModelReferenceVersionMismatchMessa' ...
                                    'ge'], 'none');
CommonModelConfiguration.set_param('MultiTaskCondExecSysMsg', 'error');
CommonModelConfiguration.set_param('MultiTaskDSMMsg', 'error');
CommonModelConfiguration.set_param('MultiTaskRateTransMsg', 'error');
CommonModelConfiguration.set_param('ParameterDowncastMsg', 'error');
CommonModelConfiguration.set_param('ParameterOverflowMsg', 'error');
CommonModelConfiguration.set_param('ParameterPrecisionLossMsg', ['warni' ...
                                    'ng']);
CommonModelConfiguration.set_param('ParameterTunabilityLossMsg', ['warn' ...
                                    'ing']);
CommonModelConfiguration.set_param('ParameterUnderflowMsg', 'none');
CommonModelConfiguration.set_param('ProdIntDivRoundTo', 'Undefined');
CommonModelConfiguration.set_param('ProfileTLC', 'off');
CommonModelConfiguration.set_param('ReadBeforeWriteMsg', ['UseLocalSett' ...
                                    'ings']);
CommonModelConfiguration.set_param('RetainRTWFile', 'off');
CommonModelConfiguration.set_param('RollThreshold', 5);
CommonModelConfiguration.set_param('RootOutportRequireBusObject', ['war' ...
                                    'ning']);
CommonModelConfiguration.set_param('RTPrefix', 'error');
CommonModelConfiguration.set_param('RTWVerbose', 'on');
CommonModelConfiguration.set_param('SignalInfNanChecking', 'none');
CommonModelConfiguration.set_param('SignalLabelMismatchMsg', 'none');
CommonModelConfiguration.set_param('SignalRangeChecking', 'none');
CommonModelConfiguration.set_param('SignalResolutionControl', ['UseLoca' ...
                                    'lSettings']);
CommonModelConfiguration.set_param('SigSpecEnsureSampleTimeMsg', ['warn' ...
                                    'ing']);
CommonModelConfiguration.set_param('SingleTaskRateTransMsg', 'none');
CommonModelConfiguration.set_param('Solver', 'VariableStepAuto');
CommonModelConfiguration.set_param('SolverPrmCheckMsg', 'warning');
CommonModelConfiguration.set_param('StartTime', '0.0');
CommonModelConfiguration.set_param('StateBitsets', 'off');
CommonModelConfiguration.set_param('StopTime', 'Inf');
CommonModelConfiguration.set_param('StrictBusMsg', 'ErrorLevel1');
CommonModelConfiguration.set_param('AlgebraicLoopMsg', 'error');
CommonModelConfiguration.set_param('TasksWithSamePriorityMsg', ['warnin' ...
                                    'g']);
CommonModelConfiguration.set_param('TLCAssert', 'off');
CommonModelConfiguration.set_param('TLCCoverage', 'off');
CommonModelConfiguration.set_param('TLCDebug', 'off');
CommonModelConfiguration.set_param('UnconnectedInputMsg', 'warning');
CommonModelConfiguration.set_param('UnconnectedLineMsg', 'warning');
CommonModelConfiguration.set_param('UnconnectedOutputMsg', 'warning');
CommonModelConfiguration.set_param('UnderSpecifiedDataTypeMsg', 'none');
CommonModelConfiguration.set_param('UnnecessaryDatatypeConvMsg', 'none');
CommonModelConfiguration.set_param('UtilityFuncGeneration', 'Auto');
CommonModelConfiguration.set_param('VectorMatrixConversionMsg', 'none');
CommonModelConfiguration.set_param('WriteAfterReadMsg', ['UseLocalSetti' ...
                                    'ngs']);
CommonModelConfiguration.set_param('WriteAfterWriteMsg', ['UseLocalSett' ...
                                    'ings']);
CommonModelConfiguration.set_param('AssertControl', 'UseLocalSettings');
CommonModelConfiguration.set_param('BlockPriorityViolationMsg', ['warni' ...
                                    'ng']);
CommonModelConfiguration.set_param('InitFltsAndDblsToZero', 'off');
CommonModelConfiguration.set_param('UseDivisionForNetSlopeComputation', ...
                                    'off');
CommonModelConfiguration.set_param('InspectSignalLogs', 'off');
CommonModelConfiguration.set_param('LogVarNameModifier', 'rt_');
CommonModelConfiguration.set_param('MemcpyThreshold', 64);
CommonModelConfiguration.set_param('PositivePriorityOrder', 'off');
CommonModelConfiguration.set_param('ProdLargestAtomicFloat', 'None');
CommonModelConfiguration.set_param('ProdLargestAtomicInteger', 'Char');
CommonModelConfiguration.set_param('MaxStep', 'auto');
CommonModelConfiguration.set_param('MinStep', 'auto');
CommonModelConfiguration.set_param('InitialStep', 'auto');
CommonModelConfiguration.set_param('RelTol', '1e-3');
CommonModelConfiguration.set_param('AbsTol', 'auto');
CommonModelConfiguration.set_param('ShapePreserveControl', 'DisableAll');
CommonModelConfiguration.set_param('MaxConsecutiveMinStep', '1');
CommonModelConfiguration.set_param('ZeroCrossControl', ['UseLocalSettin' ...
                                    'gs']);
CommonModelConfiguration.set_param('ZeroCrossAlgorithm', 'Nonadaptive');
CommonModelConfiguration.set_param('ConsecutiveZCsStepRelTol', ['10*128' ...
                                    '*eps']);
CommonModelConfiguration.set_param('ZcThreshold', 'auto');
CommonModelConfiguration.set_param('MaxConsecutiveZCs', '1000');
CommonModelConfiguration.set_param('TimeSaveName', 'tout');
CommonModelConfiguration.set_param('OutputSaveName', 'yout');
CommonModelConfiguration.set_param('SaveFormat', 'Structure');
CommonModelConfiguration.set_param('MaxDataPoints', '1000');
CommonModelConfiguration.set_param('Decimation', '1');
CommonModelConfiguration.set_param('SignalLoggingName', 'logsout');
CommonModelConfiguration.set_param('SignalLoggingSaveFormat', 'Dataset');
CommonModelConfiguration.set_param('DSMLoggingName', 'dsmout');
CommonModelConfiguration.set_param('OutputOption', 'RefineOutputTimes');
CommonModelConfiguration.set_param('Refine', '1');
CommonModelConfiguration.set_param('VisualizeSimOutput', 'on');
CommonModelConfiguration.set_param('LoggingIntervals', '[-inf, inf]');
CommonModelConfiguration.set_param('StreamToWorkspace', 'off');
CommonModelConfiguration.set_param('StreamVariableName', 'streamout');
CommonModelConfiguration.set_param('UseFloatMulNetSlope', 'off');
CommonModelConfiguration.set_param('DefaultUnderspecifiedDataType', ['d' ...
                                    'ouble']);
CommonModelConfiguration.set_param('EfficientMapNaN2IntZero', 'on');
CommonModelConfiguration.set_param('SimCompilerOptimization', 'off');
CommonModelConfiguration.set_param('AccelVerboseBuild', 'off');
CommonModelConfiguration.set_param('MaxStackSize', ['Inherit from targe' ...
                                    't']);
CommonModelConfiguration.set_param('ActiveStateOutputEnumStorageType', ...
                                    'Native Integer');
CommonModelConfiguration.set_param('MinStepSizeMsg', 'warning');
CommonModelConfiguration.set_param('TimeAdjustmentMsg', 'none');
CommonModelConfiguration.set_param('UnknownTsInhSupMsg', 'warning');
CommonModelConfiguration.set_param('ModelReferenceExtraNoncontSigs', ['e' ...
                                    'rror']);
CommonModelConfiguration.set_param('StateNameClashWarn', 'none');
CommonModelConfiguration.set_param(['SimStateInterfaceChecksumMismatchM' ...
                                    'sg'], 'warning');
CommonModelConfiguration.set_param('SimStateOlderReleaseMsg', 'error');
CommonModelConfiguration.set_param('UniqueDataStoreMsg', 'none');
CommonModelConfiguration.set_param('MergeDetectMultiDrivingBlocksExec', ...
                                    'none');
CommonModelConfiguration.set_param(['UnderspecifiedInitializationDetect' ...
                                    'ion'], 'Classic');
CommonModelConfiguration.set_param('ArrayBoundsChecking', 'none');
CommonModelConfiguration.set_param('FixptConstUnderflowMsg', 'none');
CommonModelConfiguration.set_param('FixptConstOverflowMsg', 'none');
CommonModelConfiguration.set_param('FixptConstPrecisionLossMsg', 'none');
CommonModelConfiguration.set_param('NonBusSignalsTreatedAsBus', 'none');
CommonModelConfiguration.set_param('BusNameAdapt', 'WarnAndRepair');
CommonModelConfiguration.set_param('SFcnCompatibilityMsg', 'none');
CommonModelConfiguration.set_param('FrameProcessingCompatibilityMsg', ['e' ...
                                    'rror']);
CommonModelConfiguration.set_param('SaveWithDisabledLinksMsg', ['warnin' ...
                                    'g']);
CommonModelConfiguration.set_param('SaveWithParameterizedLinksMsg', ['w' ...
                                    'arning']);
CommonModelConfiguration.set_param('SFUnusedDataAndEventsDiag', ['warni' ...
                                    'ng']);
CommonModelConfiguration.set_param('SFUnexpectedBacktrackingDiag', ['wa' ...
                                    'rning']);
CommonModelConfiguration.set_param(['SFInvalidInputDataAccessInChartIni' ...
                                    'tDiag'], 'warning');
CommonModelConfiguration.set_param(['SFNoUnconditionalDefaultTransition' ...
                                    'Diag'], 'warning');
CommonModelConfiguration.set_param(['SFTransitionOutsideNaturalParentDi' ...
                                    'ag'], 'warning');
CommonModelConfiguration.set_param(['SFUnconditionalTransitionShadowing' ...
                                    'Diag'], 'warning');
CommonModelConfiguration.set_param('SFUndirectedBroadcastEventsDiag', ['w' ...
                                    'arning']);
CommonModelConfiguration.set_param(['SFTransitionActionBeforeConditionD' ...
                                    'iag'], 'warning');
CommonModelConfiguration.set_param(['SFOutputUsedAsStateInMooreChartDia' ...
                                    'g'], 'error');
CommonModelConfiguration.set_param('EnableParallelModelReferenceBuilds', ...
                                    'off');
CommonModelConfiguration.set_param(['ParallelModelReferenceMATLABWorker' ...
                                    'Init'], 'None');
CommonModelConfiguration.set_param('ModelReferenceNumInstancesAllowed', ...
                                    'Multi');
CommonModelConfiguration.set_param('PropagateVarSize', ['Infer from blo' ...
                                    'cks in model']);
CommonModelConfiguration.set_param('EnableRefExpFcnMdlSchedulingChecks', ...
                                    'on');
CommonModelConfiguration.set_param('PropagateSignalLabelsOutOfModel', ['o' ...
                                    'ff']);
CommonModelConfiguration.set_param(['ModelReferencePassRootInputsByRefe' ...
                                    'rence'], 'on');
CommonModelConfiguration.set_param('ModelDependencies', '');
CommonModelConfiguration.set_param('SFSimEcho', 'on');
CommonModelConfiguration.set_param('SimCtrlC', 'on');
CommonModelConfiguration.set_param('SimIntegrity', 'on');
CommonModelConfiguration.set_param('SimGenImportedTypeDefs', 'off');
CommonModelConfiguration.set_param('SimBuildMode', ['sf_incremental_bui' ...
                                    'ld']);
CommonModelConfiguration.set_param('SimReservedNameArray', []);
CommonModelConfiguration.set_param('SimParseCustomCode', 'on');
CommonModelConfiguration.set_param('SimCustomSourceCode', '');
CommonModelConfiguration.set_param('SimCustomHeaderCode', '');
CommonModelConfiguration.set_param('SimCustomInitializer', '');
CommonModelConfiguration.set_param('SimCustomTerminator', '');
CommonModelConfiguration.set_param('SimUserIncludeDirs', '');
CommonModelConfiguration.set_param('SimUserSources', '');
CommonModelConfiguration.set_param('SimUserLibraries', '');
CommonModelConfiguration.set_param('TargetLang', 'C');
CommonModelConfiguration.set_param('Toolchain', ['Automatically locate ' ...
                                    'an installed toolchain']);
CommonModelConfiguration.set_param('BuildConfiguration', ['Faster Build' ...
                                    's']);
CommonModelConfiguration.set_param('ObjectivePriorities', []);
CommonModelConfiguration.set_param('CheckMdlBeforeBuild', 'Off');
CommonModelConfiguration.set_param('PackageGeneratedCodeAndArtifacts', ...
                                    'off');
CommonModelConfiguration.set_param('PackageName', '');
CommonModelConfiguration.set_param('RTWUseSimCustomCode', 'off');
CommonModelConfiguration.set_param('CustomSourceCode', '');
CommonModelConfiguration.set_param('CustomHeaderCode', '');
CommonModelConfiguration.set_param('CustomInclude', '');
CommonModelConfiguration.set_param('CustomSource', '');
CommonModelConfiguration.set_param('CustomLibrary', '');
CommonModelConfiguration.set_param('CustomInitializer', '');
CommonModelConfiguration.set_param('CustomTerminator', '');
CommonModelConfiguration.set_param('MATLABSourceComments', 'off');
CommonModelConfiguration.set_param('UseSimReservedNames', 'off');
CommonModelConfiguration.set_param('ReservedNameArray', []);
CommonModelConfiguration.set_param('CodeInterfacePackaging', ['Nonreusa' ...
                                    'ble function']);
CommonModelConfiguration.set_param('GenerateASAP2', 'off');
CommonModelConfiguration.set_param('Name', 'CommonModelConfiguration');
CommonModelConfiguration.set_param('Description', '');

